mdn/discord

module.js
Patch to add basic functionality, as per our original plan.  Still needs some work to start using diff positions in the comments, rather than just dumping them to the comment section below, and needs some fancier messages... with links and such.
r?
=> Add some functionality. Yea!

module.js
Supersedes #12 with beautification and JSHint updates.
=> all issues in a file are now in a single comment

diffParse.js, module.js, package.json
=> put comment in diff line notes instead of grouped at the bottom

README.md, app.js, landingPage.js, package.json
The marked package does not support emojis, so unfortunately this marks
the end of the "description sandwich".
=> Fix #18: Add basic project landing page

diffParse.js
=> Hoist vars to top

package.json
This should allow the ^ updates to use the release updates.
=> Bump doiuse to a release update

commenter.js
We can make our code much shorter if we're only planning to support pull requests...
This is all up for discussion
=> Only supporting pull_request allows us to shorten code

hook.js
=> Making getConfig more concise

hook.js
=> Fix Issue 83 - Treat empty .doiuse as non-existent

commenter.js
This small change separates contributed and custom modules with one
empty line in commenter.js, following the convention in hook.js and
processor.js.
=> Consistent include spacing in commenter.js

diffParse.js
This file was structured differently than the other modules, so I updated it:
1.  No `module.exports`, just used `exports`
2.  The function was defined as a var, moved it to a named function
3.  Didn't like `work` as a var name
4.  Not computing the lines numbering on each iteration.
=> Code style updates for diffParse

hook.js, processor.js
This will increase our rate-limit to 5,000 per hour but will not fix the
commenting bug. [1]
[1] https://github.com/mdn/discord/issues/87#issuecomment-120193773
=> Use the OAUTH token with octonode

.travis.yml
(Insert "I don't know what I'm doing" meme here)
This is a start...
=> Add Travis file to Discord

app.js, newrelic.js, package.json
Sooooooo...I'm not sure exactly how to test this outside of pushing.  I've followed the setup directions, as instructed.  I've set license key and app name environment variables on production.
=> Adding NewRelic coverage to discord

app.js
Getting lame test errors locally, as does travis.
=> Conditionally include new relic to avoid local errors

lib/commenter.js
Should fix posting issues with request
=> Ensuring integrity of the comment poster

gulpfile.js
The repo doesn't have any other JSON files right now, but to cover all
the bases Gulp should search for JSON throughout the repo just like it
does with JS.
=> Run all JSON (except test JSON) through beautify

.editorconfig, .travis.yml
Just a small thing I want to get out of the way before forgetting about it.
=> Enforce EditorConfig settings in YML, make updates

gulpfile.js
The beautify task formats our JavaScript to a consistent standard so
that we don't need to think about coding conventions ourselves. We
missed a "gulp beautify" run in a previous commit, so this commit
catches everything up.
=> Make outstanding "gulp beautify" changes

migrations/20160121091841-create-comment.js, models/comment.js, routes/hook/index.js, tests/test-utils.js, tests/tests.js
Combines https://github.com/mdn/discord/pull/168 and https://github.com/mdn/discord/compare/master...record-comments-97?expand=1
1. Push this branch up to your test webhook
2. Open a pull request in the repo that uses the test webhook
3. Wait about 30 seconds, refresh, and note the number of comments
4. Close the pull request, reopen it, wait a few seconds, refresh, and note the number of comments
The number of comments should not change between step 3 and step 4. No lines should be double-commented.
=> comments: record and prevent duplicates
